# Base image
FROM node:18

# Set working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the application
COPY . .

# Expose the port API Gateway runs on
EXPOSE 5000

# Start the API Gateway
CMD ["npm", "start"]
